import { Metadata } from 'next';
import Image from 'next/image';
import { memo } from 'react';

export const metadata: Metadata = {
  title: "Recipes",
  description: "Generated by create next app",
};


interface IData {
    id: string
    name: string
    rating: number
    cuisine: string
    image: string
}

const Recipes = async () => {
    const response = await fetch("https://dummyjson.com/recipes")
    const data = await response.json()
  return (
    <div className='container'>
      <p className='text-center text-[30px] max-[555px]:text-[1rem] font-medium'>Recipes</p>
      <div className="grid grid-cols-4 gap-[1rem] max-[900px]:grid-cols-3 max-[500px]:grid-cols-2 my-[30px]">
        {
          data?.recipes?.slice(0, 12).map((item: IData) => (
              <div className='shadow-lg' key={item.id}>
                  <div className='flex items-center justify-center'>
                      <Image src={item.image} alt={item.name} width={300} height={300}/>
                  </div>
                  <div className='p-[1rem] max-[555px]:p-[10px]'>
                      <p className='line-clamp-1 font-medium'>{item.name}</p>
                      <p>{item.rating} rating</p>
                      <p>{item.cuisine}</p>
                  </div>
              </div>
          ))
        }
      </div>
    </div>
  );
};

export default memo(Recipes);