import { Metadata } from 'next';
import Image from 'next/image';
import { memo } from 'react';

export const metadata: Metadata = {
  title: "Users",
  description: "Generated by create next app",
};

interface IData {
    id: string
    firstName: string
    lastName: string
    gender: string
    phone: string
    image: string
}

const User = async () => {
    const response = await fetch("https://dummyjson.com/user")
    const data = await response.json()
  return (
    <div className='container'>
      <p className='text-center text-[30px] max-[555px]:text-[1rem] font-medium'>Users</p>
      <div className="grid grid-cols-4 gap-[1rem] max-[900px]:grid-cols-3 max-[500px]:grid-cols-2 my-[30px]">
        {
          data?.users?.slice(0, 12).map((item: IData) => (
              <div className='shadow-lg' key={item.id}>
                  <div className='flex items-center justify-center'>
                      <Image src={item.image} alt={item.firstName} width={300} height={300}/>
                  </div>
                  <div className='p-[1rem] max-[555px]:p-[10px]'>
                      <p className='line-clamp-1 font-medium'>{item.firstName} {item.lastName}</p>
                      <p>{item.gender}</p>
                      <p className='line-clamp-1'>{item.phone}</p>
                  </div>
              </div>
          ))
        }
      </div>
    </div>
  );
};

export default memo(User);