import { ThumbsUp } from 'lucide-react';
import { Metadata } from 'next';
import { memo } from 'react';

export const metadata: Metadata = {
  title: "Comments",
  description: "Generated by create next app",
};


interface IData {
    id: number
    body: string
    likes: number
    user: {
      id: number
      username: string
      fullName: string
    }
}

const Comments = async () => {
    const response = await fetch("https://dummyjson.com/comments")
    const data = await response.json()
  return (
    <div className='container'>
      <p className='text-center text-[30px] max-[555px]:text-[1rem] font-medium'>Comments</p>
      <div className="grid grid-cols-4 gap-[1rem] max-[900px]:grid-cols-3 max-[500px]:grid-cols-2 my-[30px]">
        {
          data?.comments?.slice(0, 24).map((item: IData) => (
              <div className='shadow-lg' key={item.id}>
                  <div className='p-[1rem] max-[555px]:p-[10px] flex flex-col gap-[10px] max-[555px]:gap-0'>
                      <p>{item.user.fullName}</p>
                      <p className='line-clamp-1 font-medium'>{item.body}</p>
                      <div className='flex items-center gap-[10px]'>
                        <p className=''>{item.likes}</p>
                        <ThumbsUp className='size-[14px]'/>
                      </div>
                  </div>
              </div>
          ))
        }
      </div>
    </div>
  );
};

export default memo(Comments);